apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: longhorn-certificate
    namespace: longhorn-system
spec:
    secretName: longhorn
    issuerRef:
        name: acme-issuer
        kind: ClusterIssuer
    dnsNames:
        - "longhorn.trueberryless.org"
